# Lab 02 - numpy

Name: Jake Schaeffer\
Class: CSCI 349 - Intro to Data Mining\
Semester: Spring 2020\
Instructor: Brian King

In [2]:
#Setting things up ye
import sys
import numpy as np

# 1) [P] Create an 52500 x 75 matrix of zeros, stored as X. Then, print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 places of significance.

In [15]:
X = np.zeros((52500,75))
print("X Shape: {}".format(X.shape))
print("X Data type: {}".format(X.dtype))
print("X Size in bytes: %d" %X.nbytes)
print("X Size in megabytes: %.3f" %(X.nbytes/1000))

X Shape: (52500, 75)
X Data type: float64
X Size in bytes: 31500000
X Size in megabytes: 31500.000


# 2) [P] Resize X to have the same number of elements, but with 100 rows. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [18]:
X = np.resize(X,(100,X.size//100))
print("X Shape: {}".format(X.shape))
print("X Size in bytes: %d" %X.nbytes)

X Shape: (100, 39375)
X Size in bytes: 31500000


# 3) [P] Redo #1, but use a base datatype of 16-bit integers. 

You should have a reduction in memory by a factor of 4. There are times when this type of change is simple, but highly effective in speeding up your algorithm. Integer computations will always outperform floating point
computations. Use the simplest data type available that can accurately store your data.

In [19]:
X = np.zeros((52500,75), np.int16)
print("X Shape: {}".format(X.shape))
print("X Data type: {}".format(X.dtype))
print("X Size in bytes: %d" %X.nbytes)
print("X Size in megabytes: %.3f" %(X.nbytes/1000))

X Shape: (52500, 75)
X Data type: int16
X Size in bytes: 7875000
X Size in megabytes: 7875.000


# 4) [P] How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [22]:
print(X.ndim)

2


# 5) [P] Enter the following list in your cell: 
# str_nums = ['2.14', '-9.3', '42'] 
# Convert this to a numpy array named X. What is the base type? Show the contents of X. 
# Then, convert X to an array of single precision floating point numbers. (HINT: use astype). Show X again

In [3]:
str_nums = ['2.14', '-9.3', '42']
X = np.asarray(str_nums)
print("X type: ",X.dtype)
print("X: ", X)
X = X.astype(np.float32)
print("X: ", X)

X type:  <U4
X:  ['2.14' '-9.3' '42']
X:  [ 2.14 -9.3  42.  ]


# 6) [P] Copy the three definitions above for days, scores_1, and scores_2. Create a numpy array calledscores, that has scores_1 as the first row and scores_2 as the second row, using np.concatenate.Then, change days into a np.array from the list days. Show the contents of scores and days, and output their shape.

In [60]:
days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]
#create score arrays
scores_1Array = np.array(scores_1)
scores_2Array = np.array(scores_2)
#reshape into vertical arrays
scores_1Array = np.reshape(scores_1Array,(1,scores_1Array.size))
scores_2Array = np.reshape(scores_2Array,(1,scores_2Array.size))
#could maybe have used transpose?
#concatenate the vertical arrays
# idk how to do this a simpler way. this is what it said to do in the .vstack documentation
scores = np.concatenate((scores_1Array,scores_2Array))

days = np.array(days)

print("scores array: \n", scores)
print("days array: \n", days)
print("scores array shape: ", scores.shape)
print("days array shape: ", days.shape)

scores array: 
 [[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
days array: 
 ['Mon' 'Tue' 'Wed' 'Thu' 'Fri']
scores array shape:  (2, 5)
days array shape:  (5,)


# 7) [P] Repeat the previous problem with the creation of scores from scores_1 and scores_2, but repeat it with np.vstack. The array should be identical.

In [66]:
days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]

scores  = np.vstack((scores_1,scores_2))
days = np.array(days)
print("scores array: \n", scores)
print("days array: \n", days)
print("scores array shape: ", scores.shape)
print("days array shape: ", days.shape)

scores array: 
 [[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
days array: 
 ['Mon' 'Tue' 'Wed' 'Thu' 'Fri']
scores array shape:  (2, 5)
days array shape:  (5,)


# 8) [M] Compare the result of the expression days == "Fri" if the variable days was a Python list as entered above, vs. days being a numpy array. What is the difference in the result? In general, how does numpy deal with standard comparison operators?

days == "Fri" would return False with a list because the list is not equal to the string. the string "Fri" is compared to the list: days, as a whole.

days == "Fri" with days as an array would return True for the last value and False for the others.
With numpy, an operation is done on each value within the array. This is broadcasting. Thus, in numpy, the == operator on an array is checking if any of the values in days are equal to "Fri". So instead of outputting a single boolean, it will output an array of booleans that shows the result of the expression for every value in the array.

# 9) [P] Select the scores that fell on Monday.

HINT: For cells that ask for only one output, you can sometimes avoid a print statement. The expression
evaluated as the last line of a cell will also be the output of the cell. For example, if I did not use the print
function, here's what the answer would look like:

In [67]:
#get select values in scores. we use days == "Mon" in order to create an array of booleans
# that is only True for "Mon", then we use the array of booleans and only return the values 
#in scores that line up with True. Since "Mon" is the first value in the days array,
# the first value of each row of scores will be returned.
scores[:,days=="Mon"]

array([[9.5],
       [9. ]])

# 10) [P] Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)

In [74]:
# the ~ operator gives the complement (invert)
# here we are getting the complement of the array of booleans that results from the
# equality operation

scores[:,~(days=="Mon")]

#could also do 
#scores[:,days!="Mon"]

array([[ 8.75,  8.  , 10.  ,  7.75],
       [ 8.  , 10.  ,  8.75,  7.25]])

# 11) [P] Select the scores that were on Tuesday or Thursday

In [80]:
scores[:,np.logical_or(days == "Tue" ,days == "Thu")]

array([[ 8.75, 10.  ],
       [ 8.  ,  8.75]])

# 12) [P] Show the minimum and maximum scores for the entire array of scores

In [82]:
print("min score: ", np.min(scores))
print("max score: ", np.max(scores))

min score:  7.25
max score:  10.0


# 13) [P] Show the minimum scores for each week as a new array. The result should have the same dimensions 
(hint
– use the keepdims parameter).

In [83]:
# setting acis to 1 tells the min function to find the min row by row.
# setting keepdims to True means it will be kept as a two row array
scores.min(axis = 1, keepdims = True)

array([[7.75],
       [7.25]])

# 14) [P] Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to index days.)

In [91]:
week  = 1
for day in days[np.argmax(scores, axis = 1)]:
    print("Week {} max score day: {}\n".format(week,day))
    week+=1

Week 1 max score day: Thu

Week 2 max score day: Wed



# 15) [P] Report the mean of the scores of each week

In [94]:
# axis of 1 means we are looking at the mean for each row (week)
# if we set axis to 0 it would give mean for each column (day)

week = 1
for mean in np.mean(scores, axis = 1):
    print("Week {} mean score: {}\n".format(week,mean))
    week+=1

Week 1 mean score: 8.8

Week 2 mean score: 8.6



# 16) [P] Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [152]:
#axis = 1 bc we are going row by row
# find indices that contain mins
minIndices = np.argmin(scores, axis = 1)
# create an array that is scores without the mins for each row
scoresLessMins = np.delete(scores,minIndices,axis = 1)
# take the mean of each row
means = np.mean(scoresLessMins,axis = 1)

# print the result nicely - could do any number of weeks
week = 1
for mean in means:
    print("Week {} mean score without min: {}\n".format(week,mean))
    week+=1

Week 1 mean score without min: 9.0625

Week 2 mean score without min: 8.9375



# 17) [P] Convert the scores to fall on a scale from 0-100 instead of 0-10. Show the result.

In [126]:
scores * 10

array([[ 95. ,  87.5,  80. , 100. ,  77.5],
       [ 90. ,  80. , 100. ,  87.5,  72.5]])

In [153]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

# 18) [P] Select the first row of X

In [154]:
X[0]

array([48, 84, 39, 54, 77])

# 19) [P] Select the last column of X

In [157]:
X[:,-1]

array([77, 27, 59, 48, 39, 81, 66, 61, 14, 32])

# 20) [P] Select the first AND last column of X

In [180]:
#i'm not sure if this is what the question is asking. could use vstack
np.concatenate((X[:,0],X[:,-1]))

array([48, 25, 31, 93, 51, 68,  4, 76, 47, 97, 77, 27, 59, 48, 39, 81, 66,
       61, 14, 32])

# 21) [P] Select every other row of X

In [173]:
X[::2]

array([[48, 84, 39, 54, 77],
       [31, 44, 31, 27, 59],
       [51, 77, 38, 35, 39],
       [ 4,  3, 20, 13, 66],
       [47, 29, 82, 88, 14]])

# 22) [P] Show the transpose of X, but don't change X itself

In [182]:
np.transpose(X)

array([[48, 25, 31, 93, 51, 68,  4, 76, 47, 97],
       [84, 16, 44, 70, 77, 12,  3, 82, 29, 13],
       [39, 50, 31, 81, 38,  1, 20, 15, 82, 70],
       [54, 24, 27, 74, 35, 76, 13, 72, 88, 96],
       [77, 27, 59, 48, 39, 81, 66, 61, 14, 32]])

# 23) [P] Select the first column of X and set the result to Y.

In [183]:
Y = X[0]
Y

array([48, 84, 39, 54, 77])

# 24) [P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change?

THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [192]:
Y[0] +=1
print("Y: \n",Y)
print("X: \n",X)
#The value of X and Y both change

Y: 
 [52 84 39 54 77]
X: 
 [[52 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]


# 25) [P] Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y
again and ensure that the corresponding value of X did not change.

In [197]:
Y = np.copy(X[0])
print("Y first value: ",Y[0])
print("X first value: ",X[0][0])
print("\nincrementing the first value in Y by 1...\n")
Y[0]+=1
print("Y first value: ",Y[0])
print("X first value: ",X[0][0])

Y first value:  52
X first value:  52

incrementing the first value in Y by 1...

Y first value:  53
X first value:  52


# 26) [P] Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.

In [202]:
X = np.reshape(np.arange(0,10,.1),(10,10))
X

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

# 27) [P] Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [209]:
np.random.seed(1234)
X = np.linspace(1.0,10.0,100)
print("X mean = ",np.mean(X))
print("X min = ", np.min(X))
print("X max = ", np.max(X))

X mean =  5.5
X min =  1.0
X max =  10.0


# 28) [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?

The normal distribution is often found in nature. For instance, human heights are well documented to follow an approximately normal distribution for each sex.

A normal distribution's mean and standard deviation can be used to find the percentage of values in any given area of the distribution. This is because a normal distribution is distributed according to how many standard deviations a value is from the mean (often called the Z score). 

Often people refer to the 68 - 95 - 99.7 rule when talking about the normal distribution. This refers to the fact that 68% of values are within one standard deviation of the mean, 95% within 2, and 99.7% within 3.

[ref](https://www.investopedia.com/terms/n/normaldistribution.asp)

# 29) [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

As we get more and more values (i.e. sample size grows), the average (mean) of the distribution will get closer to the average of the population (the "actual" average). In terms of a normal distribution, the more values used, the closer the average of the distribution will be to the actual average.


# 30) [P] Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers. It should have four parameters:
mu = mean of distribution\
sd = standard deviation\
vec_length = length of the vector to generate randomly from a normal distribution, with mu and sd as
parameters\
num_trials = number of times to repeat the experiment\

The function should behave as follows. First, initialize the seed value to 1234, before your loop. Then, loop for
num_trials, generating vec_length numbers from a normal distribution. Compute the mean of that
vector, then compute its deviation (absolute value of the observed mean - expected mean). This should be
repeated for all trials, and then return the average deviation over all trials.

In [233]:
# this shows the Central Limit Theorem in action! I think....

def test_normal_dist(mu, sd, vec_length, num_trials):
    np.random.seed(1234)
    deviationsTotal = 0
    for trial in range(num_trials):
        mean = np.mean(np.random.normal(mu,sd,vec_length))
        deviationsTotal += abs(mean-mu)
    return deviationsTotal/num_trials

# 31) [P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. 

Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two
dimensions. the first being the vector length, and the second being the average deviation resulting from your
test_normal_dist function. Your resulting array should look like:

In other words, your results should confirm the Law of Large Numbers.

In [234]:
np.set_printoptions(suppress=True)
#https://kite.com/python/answers/how-to-format-how-a-numpy-array-prints-in-python
a = np.array(((10, test_normal_dist(0,1,10,100)),
              (100, test_normal_dist(0,1,100,100)),
              (1000, test_normal_dist(0,1,1000,100)),
              (10000, test_normal_dist(0,1,10000,100))))

print(a)

[[   10.             0.23862042]
 [  100.             0.08096253]
 [ 1000.             0.02229   ]
 [10000.             0.00794419]]


This result confirms that Law of Large Numbers because as the number of trials gets larger, the average deviation gets smaller and smaller; meaning that as the number of trials increases, the mean of the trials gets closer to the actual mean.