# Lab01 - Getting Started

Name: Jake Schaeffer

Class: CSCI349 - Intro to Dating Mining

Semester 2020SP

Instructor: Brian King

In [44]:
import sys
print(sys.version)

3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]


# 2. Did you read the syllabus? All of it? Do you agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating.

Yes. Yes. Yes. I will only submit work that is my own or created by my team.

# 3. What are you hoping to get out of this course?

I want to learn about how to clean data in order to gather meaningful insights .

# 4. Print the Python version (available in sys package)

In [45]:
import sys
print(sys.version)

3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]


# 5.Create a Python list of 10000 random integers in the range 1 to 100, using the random package. Name the list x_list.

In [46]:
import random
x_list = [random.randint(1,100) for i in range(1000)]

# 6. What is the minimum value of x_list? What is the max value? What is the mode?

In [47]:
from statistics import mode

print("The min value of x_list is {}.".format(min(x_list)))
print("The max value of x_list is {}.".format(max(x_list)))
print("The mode of x_list is {}.".format(mode(x_list)))

The min value of x_list is 1.
The max value of x_list is 100.
The mode of x_list is 15.


# 7. Write a function to take a list of numbers as a parameter, and return the average of the list. Then, use your function to report the average value of x_list, printed as a float with 2 places of precision.

In [48]:
def avg(numList):
    sum = 0
    for num in numList:
        sum +=num
    return sum / len(numList)

print("The average of x_list is %4.2f." %avg(x_list))

The average of x_list is 50.53.


# 8. Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of x_list. Each entry in x_hist should contain the range of data in widths of 10. So, x_hist[0] represents the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers between 11-20, and so on. Be sure to print x_hist at the end.

In [49]:
#init the list as a list containing 10 0s
x_hist = [0]*10 
for num in x_list:
    index = (num-1)//10
    x_hist[index] += 1
    
print(x_hist)

[99, 104, 111, 98, 95, 76, 105, 97, 110, 105]


# 9. What is numpy? What are its strengths? Does it have any weaknesses?

- For the following problems, I use [numpy documentation](docs.scipy.org) as a reference - 


numpy is a handy package for scientific computing. numpy offers many of the advantages that languages like C, which have less overhead, offer in terms of efficiency, while still allowing us to use python as our language of choice. This is done using vectorization and broadcasting.

In terms of weaknesses , indexing like this: x[index] may be considered slow. I am not sure.

[ref](https://cyrille.rossant.net/whats-wrong-with-scientific-python/)

# 10. Import the numpy package as np and print the numpy version

In [50]:
import numpy as np

print(np.version.version)

1.16.5


# 11. What is the primary object type in numpy? Can it store data of different types? Discuss.

It uses a data type called a multidimensional array as the core object, called an ndarray. It can store data of different types. For instance, it can store integers or floats. These arrays contain elements that are all of the same type. A dtype can be made to be used in a ndarray.

# 12. [M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how the type system is different than the built-in types int and float in Python.

numpy contains the primitive types supported by C because it is built using C. It contains many more numeric types than python. Instead of just int and float, it has many different levels of each that can contain different amounts of data.

# 13. [P] Create a numpy array from x_list. Reassign it as x_list. Show the contents.

In [51]:
x_list = np.array(x_list)
x_list

array([ 46,  66,  90,  75,  75,   2,  34,   2,  62,  42,  74,  89,  41,
        15,  53,  43,  14,  81,  95,  18,  66,  27,  90,   8,  73,  57,
        97,  21,  32,  99,  28,  90,  41,  30,  39,  99,  21,  82,  46,
        86,  45,  71,  86,  83,  24,  24,  48,  66,  92,  91,  30,  54,
        59,  27,  84,  12,  52,  56,  31,  50,  55,  36,  13,  57,  91,
        42,  85,  26,  34,  26,  73,  68,  72,  65,  49,  95,  27,  23,
       100,  10,  46,  98,  26,  57,  96,   3,  31,  28,  71,  82,  87,
       100,  22,  27,  88,  50,  75,  61,  70,  71,  16,  17,  15,  84,
        60,  39,  94,  71,  62,   9,  55,  75,  37,  85,  77,  49,  97,
        57,  18,  68,  30,  47,  66,   9,   9,  91,  41,  56,  66,  15,
        34,  85,  34,  84,  21,  94,  70,  33,  35,  42,  26,  17,  80,
        69,  63,  38,  45,  96,   3,  69,  43,  45,  52,  35,  77,  61,
         5,  20,   7,  23,  57,  17,  27,  66,  10,  12,  29,  67,  37,
        19,  12,  46,  12,  54,   6,  11,  98,  31,  23,  51,  9

# 14. [P] Redo the previous exercise, but set the data type of each value to 'float32'

In [52]:
x_list = np.array(x_list).astype("float32")
x_list

array([ 46.,  66.,  90.,  75.,  75.,   2.,  34.,   2.,  62.,  42.,  74.,
        89.,  41.,  15.,  53.,  43.,  14.,  81.,  95.,  18.,  66.,  27.,
        90.,   8.,  73.,  57.,  97.,  21.,  32.,  99.,  28.,  90.,  41.,
        30.,  39.,  99.,  21.,  82.,  46.,  86.,  45.,  71.,  86.,  83.,
        24.,  24.,  48.,  66.,  92.,  91.,  30.,  54.,  59.,  27.,  84.,
        12.,  52.,  56.,  31.,  50.,  55.,  36.,  13.,  57.,  91.,  42.,
        85.,  26.,  34.,  26.,  73.,  68.,  72.,  65.,  49.,  95.,  27.,
        23., 100.,  10.,  46.,  98.,  26.,  57.,  96.,   3.,  31.,  28.,
        71.,  82.,  87., 100.,  22.,  27.,  88.,  50.,  75.,  61.,  70.,
        71.,  16.,  17.,  15.,  84.,  60.,  39.,  94.,  71.,  62.,   9.,
        55.,  75.,  37.,  85.,  77.,  49.,  97.,  57.,  18.,  68.,  30.,
        47.,  66.,   9.,   9.,  91.,  41.,  56.,  66.,  15.,  34.,  85.,
        34.,  84.,  21.,  94.,  70.,  33.,  35.,  42.,  26.,  17.,  80.,
        69.,  63.,  38.,  45.,  96.,   3.,  69.,  4

# 15. [P] Create a length 10 integer array filled with zeros

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 16. [P] Create a float array of 3 rows and 4 columns, all initialized to one.

In [54]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 17. [P] Create an array of 20 values, evenly spaced between 1 and 3 (HINT – look at np.linspace)

In [41]:
np.linspace(1,3,20)

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

# 18. [P] Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the interval [10, 20)

In [55]:
np.random.seed(12345)
np.random.randint(10,20,(10,5))

array([[12, 15, 11, 14, 19],
       [15, 12, 11, 16, 11],
       [19, 17, 16, 10, 12],
       [19, 11, 12, 16, 17],
       [17, 17, 18, 17, 11],
       [17, 14, 10, 13, 15],
       [17, 13, 11, 15, 12],
       [15, 13, 18, 15, 12],
       [15, 13, 10, 16, 18],
       [10, 15, 16, 18, 19]])